Post endpoint clarification
bookmd/code-interview pull request #30
Opened 2021-01-19 00:10 UTC by ilanbenb

2021-01-19 06:18 UTC, PeledYuval approved these changes

2021-01-19 06:18 UTC, PeledYuval requested changes
1 small typo :)

2021-01-19 06:18 UTC, PeledYuval commented on readme.md
> +  * This endpoint does not actually changes the providers data, they will be mutated in the bonus part ;).
"changes" -> "change"

2021-01-24 20:12 UTC, ilanbenb commented on readme.md
> +  * This endpoint does not actually changes the providers data, they will be mutated in the bonus part ;).
```suggestion
  * This endpoint does not actually change the providers data, they will be mutated in the bonus part ;).
```

2021-01-24 20:13 UTC, merged